### ISSUE TITLE
Invalid type <class 'NoneType'> 

### ISSUE THREAD

**Issue by clannadcl** [microsoft/Swin-Transformer#102]
Traceback (most recent call last):                                                                                                                                                                     
  File "main.py", line 21, in <module>                                                                                                                                                                 
    from config import get_config                                                                                                                                                                      
  File "/root/paddlejob/workspace/env_run/video_tag/code/swin/config.py", line 70, in <module>                                                                                                         
    _C.MODEL.SWIN.QK_SCALE = None                                                                                                                                                                      
  File "/root/paddlejob/workspace/env_run/video_tag/food/lib/python3.7/site-packages/yacs/config.py", line 158, in __setattr__                                                                         
    type(value), name, _VALID_TYPES                                                                                                                                                                    
  File "/root/paddlejob/workspace/env_run/video_tag/food/lib/python3.7/site-packages/yacs/config.py", line 521, in _assert_with_logging                                                                
    assert cond, msg                                                                                                                                                                                   
AssertionError: Invalid type <class 'NoneType'> for key QK_SCALE; valid types = {<class 'float'>, <class 'tuple'>, <class 'int'>, <class 'str'>, <class 'bool'>, <class 'list'>}

**Comment by sunguwei** [comment]
same question, how did you solve it?

**Comment by SRN200722** [comment]
Have you solve it?I meet the same question

**Comment by SRN200722** [comment]
> same question, how did you solve it?
Have you solve it?I meet the same question

**Comment by sblack15** [comment]
update yacs to latest version 

    ``pip install yacs -U

**Comment by ancientmooner** [comment]
Thanks @sblack15
