### ISSUE TITLE
classification Evaluation code error AttributeError: 'NoneType' object has no attribute 'initialize' How can I solve it?

### ISSUE THREAD

**Issue by youngdaragon** [microsoft/Swin-Transformer#177]
Hi, i used evaluation classification code , but I get an error. 
Traceback (most recent call last):
  File "main.py", line 357, in <module>
    main(config)
  File "main.py", line 89, in main
    model, optimizer = amp.initialize(model, optimizer, opt_level=config.AMP_OPT_LEVEL)
AttributeError: 'NoneType' object has no attribute 'initialize'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 93793) of binary: /home/kimyongtae/Downloads/myAnaconda/envs/myenv/bin/python
Traceback (most recent call last):
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kimyongtae/Downloads/myAnaconda/envs/myenv/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-03-04_13:30:27
  host      : kimyongtae-B250-HD3
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 93793)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

How can I solve it?

**Comment by gcunhase** [comment]
Did you resolve this?

**Comment by youngdaragon** [comment]
yes i solved it. it's problem is gpu lank. i use single gpu, but i was gpu lank settings multigpu. so i change gpu lank.

**Comment by gcunhase** [comment]
How did you solve it?
