### ISSUE TITLE
Issue trying to use MoBY SLL pretrained model with SWIN T backbone

### ISSUE THREAD

**Issue by Giles-Billenness** [microsoft/Swin-Transformer#181]
When trying to load the checkpoint after SLL pretraining with MoBY I get this error after using the `--pretrained` flag pointing to the checkpoint. I am trying to transfer self-supervised learning with the same backbone to this architecture.

`Traceback (most recent call last):
  File "/content/Swin-Transformer/main.py", line 357, in <module>
    main(config)
  File "/content/Swin-Transformer/main.py", line 131, in main
    load_pretrained(config, model_without_ddp, logger)
  File "/content/Swin-Transformer/utils.py", line 70, in load_pretrained
    relative_position_bias_table_current = model.state_dict()[k]
KeyError: 'encoder.layers.0.blocks.0.attn.relative_position_bias_table'
Killing subprocess 3303`

**Comment by Giles-Billenness** [comment]
Was able to load a checkpoint somewhat by changing the loading code:

1. adding the lines
```
def load_pretrained(config, model, logger):
    logger.info(f"==============> Loading weight {config.MODEL.PRETRAINED} for fine-tuning......")
    checkpoint = torch.load(config.MODEL.PRETRAINED, map_location='cpu')
    state_dict = checkpoint['model']

>    if sorted(list(state_dict.keys()))[0].startswith('encoder'):
>     state_dict = {k.replace('encoder.', ''): v for k, v in state_dict.items() if k.startswith('encoder.')}
```

**Comment by Giles-Billenness** [comment]
I also found after these changes that when loading pre-trained models from this repo (swin_tiny_patch4_window7_224.pth) such as from ImageNet a similar log is shown
```
_IncompatibleKeys(missing_keys=['layers.0.blocks.0.attn.relative_position_index', 'layers.0.blocks.1.attn_mask', 'layers.0.blocks.1.attn.relative_position_index', 
                                'layers.1.blocks.0.attn.relative_position_index', 'layers.1.blocks.1.attn_mask', 'layers.1.blocks.1.attn.relative_position_index', 
                                'layers.2.blocks.0.attn.relative_position_index', 'layers.2.blocks.1.attn_mask', 'layers.2.blocks.1.attn.relative_position_index', 
                                'layers.2.blocks.2.attn.relative_position_index', 'layers.2.blocks.3.attn_mask', 'layers.2.blocks.3.attn.relative_position_index', 
                                'layers.2.blocks.4.attn.relative_position_index', 'layers.2.blocks.5.attn_mask', 'layers.2.blocks.5.attn.relative_position_index', 
                                'layers.3.blocks.0.attn.relative_position_index', 'layers.3.blocks.1.attn.relative_position_index'], unexpected_keys=[])
```

**Comment by Giles-Billenness** [comment]
Ah, these are all re init'ed anyway and so it doesn't matter. I might open a PR to allow for use of MoBY pre-trained models.

**Comment by kavin-du** [comment]
same issue..

**Comment by kavin-du** [comment]
same issue when using MoBY pretrained models..
