### ISSUE TITLE
about gpu

### ISSUE THREAD

**Issue by mc171819** [microsoft/Swin-Transformer#20]
hi！Which and how many gpus did you use when you train each(Swin-T,S,B,L) model?

**Comment by wiekern** [comment]
give a try by yourself. I have single GTX1080Ti card about 12GB, on which a Swin-T can be trained with batch-size 64. Without setting batch-size explicitly you might meet an error "CUDA out of memory".

**Comment by ancientmooner** [comment]
It you want to have larger batch size, you can try the accumulate_gradient argument.

**Comment by AnthonyFang623** [comment]
> 

I have a problem with training my data by using single GPU, my commends are as follow, could you tell me how to train my model on my own data please?

python -m torch.distributed.launch --master_port 12345  main.py
--cfg swin_base_patch4_window7_224.yaml --data-path "my data dir" --batch-size 64
--accumulation-steps 2 [--use-checkpoint]

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from timm.loss import LabelSmoothingCrossEntropy, SoftTargetCrossEntropy
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\timm\__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\timm\models\__init__.py", line 1, in <module>
    from .cspnet import *
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\timm\models\cspnet.py", line 20, in <module>
    from .helpers import build_model_with_cfg
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\timm\models\helpers.py", line 17, in <module>
    from .layers import Conv2dSame, Linear
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\timm\models\layers\__init__.py", line 7, in <module>
    from .cond_conv2d import CondConv2d, get_condconv_initializer
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\timm\models\layers\cond_conv2d.py", line 16, in <module>
    from .helpers import to_2tuple
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\timm\models\layers\helpers.py", line 6, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\torch\_six.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 9808) of binary: C:\Users\DSP03\anaconda3\envs\swin\python.exe
Traceback (most recent call last):
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\torch\distributed\run.py", line 710, in run
    elastic_launch(
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\DSP03\anaconda3\envs\swin\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
