### ISSUE TITLE
window kernel compile error

### ISSUE THREAD

**Issue by Hanqer** [microsoft/Swin-Transformer#243]
env:   ubuntau 20.04, pytorch==1.11.0, cuda_version=10.2

error logs: 

Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 489, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 456, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/home/hanqi/miniconda3/envs/glom/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

**Comment by tyleryzhu** [comment]
The list "arch_list" is empty most likely because it does have any cuda devices visible to it. You should work in an environment with the gpu you want to use so it can compile the kernel.

**Comment by jieruyao49** [comment]
I meet same problem, have you solve it？

**Comment by tyleryzhu** [comment]
You most likely are trying to compile when there are no GPUs available. Try checking with  `nvidia-smi`.
