### ISSUE TITLE
Invalid type <class 'NoneType'> for key QK_SCALE;  C.AUG.CUTMIX_MINMAX

### ISSUE THREAD

**Issue by ly59782** [microsoft/Swin-Transformer#95]
I use the deafult config and meet error, It seems like the parameters in config.py cannot be set to None，
I don't know why. please help me，many thanks

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from config import get_config
  File "/root/WangYan/Swin-Transformer-main/config.py", line 72, in <module>
    _C.MODEL.SWIN.QK_SCALE = None
  File "/root/.local/conda/envs/swin/lib/python3.7/site-packages/yacs/config.py", line 158, in __setattr__
    type(value), name, _VALID_TYPES
  File "/root/.local/conda/envs/swin/lib/python3.7/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key QK_SCALE; valid types = {<class 'float'>, <class 'tuple'>, <class 'int'>, <class 'str'>, <class 'bool'>, <class 'list'>}
Traceback (most recent call last):
  File "/root/.local/conda/envs/swin/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/.local/conda/envs/swin/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/root/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/.local/conda/envs/swin/bin/python', '-u', 'main.py', '--local_rank=0', '--cfg', 'configs/swin_base_patch4_window7_224.yaml', '--resume', 'checkpoints/swin_base_patch4_window7_224_22k.pth']' returned non-zero exit status 1.

config.py:
_C.MODEL.SWIN.QKV_BIAS = True
_C.MODEL.SWIN.QK_SCALE = None ####################
_C.MODEL.SWIN.APE = False
_C.MODEL.SWIN.PATCH_NORM = True
......................................
_C.AUG.CUTMIX_MINMAX = None ###################

The above two parameters are all wrong.

**Comment by ly59782** [comment]
i uninstall yacs and reinstall yacs==0.8.1 sloved

**Comment by flybiubiu** [comment]
> i uninstall yacs and reinstall yacs==0.8.1 sloved

yacs==0.1.8
